version: '2'
services:
  caffe-jupyter-notebooks:
    build: caffe 
#    restart: always
    ports:
     - "8895:8888"
    command: [ "jupyter-notebook", "--no-browser", "--port=8888", "--ip=0.0.0.0", "--allow-root"]
